### ISSUE TITLE
Unable to select mode in Firefox 47.0.1

### ISSUE THREAD

**Issue by unclesnottie** [Kowalski-IO/claptrap#6]
I am able to select the mode in Chrome 51.0.2704.103 but not in Firefox 47.0.1 both on OSX.  In FF, selecting the mode does nothing.  The following error displays in the Firebug console:

![firebug_-_claptrap](https://cloud.githubusercontent.com/assets/130180/16804382/89d57c74-48d9-11e6-9788-afbb4b692c0d.png)

**Comment by BrandonKowalski** [comment]
@sskeller I'll take a look. Thanks!

**Comment by BrandonKowalski** [comment]
Will ensure cross version support for Evergreen browsers in 3.0.0 release.
